### PR TITLE
fix: build failure

### PR DESCRIPTION
**Pull request by takaishi**
goreleaser failed after merging https://github.com/reproio/send-alb-metrics-to-datadog/pull/37 and https://github.com/reproio/send-alb-metrics-to-datadog/pull/38 . I fix it.

```
  ⨯ release failed after 1m33s               error=failed to build for linux_arm64: exit status 1: # command-line-arguments
Error: ./main.go:26:20: undefined: NewProcessor
Error: ./main.go:48:20: undefined: NewProcessor

Error: The process '/opt/hostedtoolcache/goreleaser-action/1.23.0/x64/goreleaser' failed with exit code 1
```

### CODE REVIEW

File: .goreleaser.yml [hunk 1]
```diff
@@ -5,7 +5,7 @@ before:
   hooks:
     - go mod tidy
 builds:
-  - main: main.go
+  - main: .
```
Comment (okkez) [inline .goreleaser.yml:8]: :memo:
>  Default is `.`.
https://goreleaser.com/customization/builds/

**Review by okkez — APPROVED** [review]

**Comment by takaishi** [comment]
thanks!
